'use client'

import {useEffect,useRef,useState} from 'react'
import type {MalaysiaSamplePrefill} from '@/lib/request-sample/malaysia-request-sample-prefill'
import {submitMalaysiaSampleRequest} from '@/lib/request-sample/malaysia-request-sample-receiver'
import {emptyMalaysiaSampleRequestValues,validateMalaysiaSampleRequest,type MalaysiaSampleRequestErrors,type MalaysiaSampleRequestValues} from '@/lib/request-sample/malaysia-request-sample-validation'
import type {MalaysiaRequestSamplePageDto} from '@/lib/wordpress/request-sample-v01-types'
import styles from './malaysia-request-sample-page.module.css'

interface Props{readonly page:MalaysiaRequestSamplePageDto;readonly prefill:MalaysiaSamplePrefill;readonly receiverReady:boolean}
type State='ready'|'submitting'|'failure'|'success'|'unavailable'
type Field=keyof MalaysiaSampleRequestValues
const labels:Record<Field,string>={grade_id:'Product grade',application_id:'Application',application_other:'Describe the application',test_objective:'What do you need to evaluate?',current_grade_or_target:'Current grade or target requirement',contact_name:'Contact name',company_organisation:'Company or organisation',business_email:'Business email',destination_country_market:'Destination country or market',expected_project_annual_use:'Expected project or annual use',documents_needed:'Documents needed for the trial',additional_context:'Additional non-confidential context'}
const processLabels:Record<NonNullable<MalaysiaSamplePrefill['process_context']>,string>={chloride:'Chloride',sulfate:'Sulfate','vapor-phase-oxidation':'Vapor-phase oxidation'}

export function createSampleRequestIdempotencyKey(cryptoApi:Crypto|undefined=globalThis.crypto):string{
  if(cryptoApi?.randomUUID)return cryptoApi.randomUUID()
  if(!cryptoApi?.getRandomValues)throw new Error('A secure UUID generator is required')
  const bytes=cryptoApi.getRandomValues(new Uint8Array(16));bytes[6]=((bytes[6]??0)&15)|64;bytes[8]=((bytes[8]??0)&63)|128
  const hex=[...bytes].map((byte)=>byte.toString(16).padStart(2,'0')).join('');return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`
}

export function MalaysiaRequestSampleForm({page,prefill,receiverReady}:Props){
  const [values,setValues]=useState<MalaysiaSampleRequestValues>({...emptyMalaysiaSampleRequestValues,grade_id:prefill.grade_id??'',application_id:prefill.application_id??'',destination_country_market:prefill.destination??'',documents_needed:prefill.documents_needed??[]})
  const [context,setContext]=useState({source_page_id:prefill.source_page_id,market_id:prefill.market_id,process_context:prefill.process_context,resource_context:prefill.resource_context})
  const [visible,setVisible]=useState({grade:Boolean(prefill.grade_id),application:Boolean(prefill.application_id),destination:Boolean(prefill.destination),documents:Boolean(prefill.documents_needed?.length),process:Boolean(prefill.process_context),resource:Boolean(prefill.resource_context)})
  const [errors,setErrors]=useState<MalaysiaSampleRequestErrors>({});const [state,setState]=useState<State>('ready');const [attempt,setAttempt]=useState(0)
  const summaryRef=useRef<HTMLDivElement>(null);const stateRef=useRef<HTMLDivElement>(null);const keyRef=useRef<string|null>(null);const pendingRef=useRef(false)
  useEffect(()=>{if(attempt)summaryRef.current?.focus()},[attempt]);useEffect(()=>{if(['failure','success','unavailable'].includes(state))stateRef.current?.focus()},[state])
  const rotate=()=>{keyRef.current=null;if(state==='failure'||state==='unavailable')setState('ready')}
  const update=(field:Exclude<Field,'documents_needed'>,value:string)=>{rotate();setValues((current)=>({...current,[field]:value}));if(errors[field]||(field==='application_id'&&value!=='other'&&errors.application_other))setErrors((current)=>({...current,[field]:undefined,...(field==='application_id'&&value!=='other'?{application_other:undefined}:{})}))}
  const toggleDocument=(value:string)=>{rotate();setValues((current)=>({...current,documents_needed:current.documents_needed.includes(value)?current.documents_needed.filter((item)=>item!==value):[...current.documents_needed,value]}));if(errors.documents_needed)setErrors((current)=>({...current,documents_needed:undefined}))}
  const remove=(kind:keyof typeof visible)=>{rotate();setVisible((current)=>({...current,[kind]:false}));if(kind==='grade')update('grade_id','');if(kind==='application')update('application_id','');if(kind==='destination')update('destination_country_market','');if(kind==='documents')setValues((current)=>({...current,documents_needed:[]}));if(kind==='process')setContext((current)=>({...current,process_context:undefined}));if(kind==='resource')setContext((current)=>({...current,resource_context:undefined}))}
  const focusField=(field:Field)=>field==='documents_needed'?document.querySelector<HTMLInputElement>('#sample-documents input')?.focus():document.getElementById(`sample-${field}`)?.focus()

  async function performSubmission(){
    if(pendingRef.current)return;pendingRef.current=true;setErrors({});setState('submitting')
    try{keyRef.current??=createSampleRequestIdempotencyKey();const result=await submitMalaysiaSampleRequest(values,{accessKey:process.env.NEXT_PUBLIC_TIO2_MY_WEB3FORMS_ACCESS_KEY??null,idempotencyKey:keyRef.current,sourceContext:context})
      if(result.kind==='receipt_confirmed')setState('success')
      else if(result.kind==='validation_failed'&&Object.keys(result.errors).length){setErrors(result.errors);setState('ready');setAttempt((value)=>value+1)}
      else if(result.kind==='unavailable')setState('unavailable');else setState('failure')
    }catch{setState('failure')}finally{pendingRef.current=false}
  }
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(pendingRef.current)return;const next=validateMalaysiaSampleRequest(values);if(Object.keys(next).length){setErrors(next);setState('ready');setAttempt((value)=>value+1);return}await performSubmission()}
  const described=(field:Field,helper=false)=>[helper?`sample-${field}-helper`:null,errors[field]?`sample-${field}-error`:null].filter(Boolean).join(' ')||undefined
  const contextVisible=Object.values(visible).some(Boolean)

  if(!receiverReady)return <section className={styles.formSurface} data-module="sample-request" aria-labelledby="sample-unavailable-heading"><div className={`${styles.statePanel} ${styles.unavailable}`}><h2 id="sample-unavailable-heading">{page.form.unavailable.heading}</h2><p>{page.form.unavailable.body}</p></div></section>

  return <>
    {contextVisible&&<section className={styles.prefill} aria-labelledby="sample-prefill-heading" data-module="prefill-context"><h2 id="sample-prefill-heading">{page.prefill.heading}</h2><p>{page.prefill.body}</p><div className={styles.prefillGrid}>
      {visible.grade&&<Context label="Grade" targetId="sample-grade_id" value={values.grade_id} onRemove={()=>remove('grade')}/>} {visible.application&&<Context label="Application" targetId="sample-application_id" value={page.form.applicationOptions.find((item)=>item.value===values.application_id)?.label??values.application_id} onRemove={()=>remove('application')}/>} {visible.process&&context.process_context&&<Context label="Process context" value={processLabels[context.process_context]} onRemove={()=>remove('process')} removeOnly/>} {visible.destination&&<Context label="Destination" targetId="sample-destination_country_market" value={values.destination_country_market} onRemove={()=>remove('destination')}/>} {visible.documents&&<Context label="Documents" targetId="sample-documents" value={values.documents_needed.map((value)=>page.form.documentOptions.find((item)=>item.value===value)?.label??value).join(', ')} onRemove={()=>remove('documents')}/>} {visible.resource&&context.resource_context&&prefill.resource_context_label&&<Context label="Resource context" value={prefill.resource_context_label} onRemove={()=>remove('resource')} removeOnly/>}
    </div></section>}
    <section className={styles.formSurface} data-module="sample-request" aria-labelledby="sample-form-heading">
      <form className={styles.form} aria-label="Request a Sample" aria-busy={state==='submitting'||undefined} onSubmit={submit} noValidate>
        <p className={styles.eyebrow}>{page.form.eyebrow}</p><h2 id="sample-form-heading">{page.form.heading}</h2><p className={styles.formIntro}>{page.form.intro}</p><p className={styles.warning}>{page.form.warning}</p>
        {Object.keys(errors).length>0&&<div ref={summaryRef} tabIndex={-1} role="alert" className={styles.errorSummary}><h3>{page.form.errors.summary}</h3><ul>{Object.entries(errors).map(([field,message])=><li key={field}><a href={`#sample-${field}`} onClick={(event)=>{event.preventDefault();focusField(field as Field)}}>{labels[field as Field]}: {message}</a></li>)}</ul></div>}
        {state==='unavailable'?<StatePanel refValue={stateRef} kind="unavailable" heading={page.form.unavailable.heading} body={page.form.unavailable.body}/>:state==='success'?<StatePanel refValue={stateRef} kind="success" heading={page.form.success.heading} body={page.form.success.body}/>:<>
        <fieldset disabled={state==='submitting'}><legend><span><b>01</b> {page.form.sections[0]}</span></legend><div className={styles.fieldGrid} data-field-grid>
          <SelectField id="grade_id" label="Product grade" value={values.grade_id} error={errors.grade_id} describedBy={described('grade_id')} onChange={(value)=>update('grade_id',value)}><option value="">Choose a grade</option>{page.form.gradeOptions.map((grade)=><option key={grade} value={grade}>{grade==='unknown'?'I do not know the grade':grade}</option>)}</SelectField>
          <SelectField id="application_id" label="Application" value={values.application_id} error={errors.application_id} describedBy={described('application_id')} onChange={(value)=>update('application_id',value)}><option value="">Choose an application</option>{page.form.applicationOptions.map((item)=><option key={item.value} value={item.value}>{item.label}</option>)}</SelectField>
          {values.application_id==='other'&&<TextArea field="application_other" label="Describe the application" required value={values.application_other} error={errors.application_other} onChange={update}/>}
          <TextArea field="test_objective" label="What do you need to evaluate?" required value={values.test_objective} error={errors.test_objective} helper="Describe the result, processing question or trial objective you need to assess. Do not include a confidential formulation." placeholder="Describe the result, processing question or trial objective you need to assess." onChange={update}/>
          <TextField field="current_grade_or_target" label="Current grade or target requirement" value={values.current_grade_or_target} error={errors.current_grade_or_target} helper="Share a non-confidential reference point if it will help the review." placeholder="Share a non-confidential reference point if it will help the review." onChange={update}/>
        </div></fieldset>
        <fieldset disabled={state==='submitting'}><legend><span><b>02</b> {page.form.sections[1]}</span></legend><div className={styles.fieldGrid} data-field-grid>
          <TextField field="contact_name" label="Contact name" required autoComplete="name" value={values.contact_name} error={errors.contact_name} onChange={update}/><TextField field="company_organisation" label="Company or organisation" required autoComplete="organization" value={values.company_organisation} error={errors.company_organisation} onChange={update}/><TextField field="business_email" label="Business email" type="email" required autoComplete="email" value={values.business_email} error={errors.business_email} helper="Use an address where we can contact you about this request." onChange={update}/><TextField field="destination_country_market" label="Destination country or market" required autoComplete="country-name" value={values.destination_country_market} error={errors.destination_country_market} placeholder="Enter your destination country or market" helper="Enter the country or market relevant to this evaluation." onChange={update}/>
        </div></fieldset>
        <fieldset disabled={state==='submitting'}><legend><span><b>03</b> {page.form.sections[2]}</span></legend><div className={styles.fieldGrid} data-field-grid><TextField field="expected_project_annual_use" label="Expected project or annual use" value={values.expected_project_annual_use} error={errors.expected_project_annual_use} helper="This is project context, not a requested sample quantity." onChange={update}/></div>
          <fieldset id="sample-documents" tabIndex={-1} className={styles.documents} data-sample-field="documents_needed" aria-invalid={Boolean(errors.documents_needed)} aria-describedby={described('documents_needed',true)}><legend>Documents needed for the trial <small>Optional</small></legend><div>{page.form.documentOptions.map((item)=><label key={item.value}><input type="checkbox" value={item.value} checked={values.documents_needed.includes(item.value)} onChange={()=>toggleDocument(item.value)}/><span>{item.label}</span></label>)}</div><p id="sample-documents_needed-helper" className={styles.helper}>Selection does not confirm document availability or release.</p>{errors.documents_needed&&<p id="sample-documents_needed-error" className={styles.fieldError}>{errors.documents_needed}</p>}</fieldset>
          <TextArea field="additional_context" label="Additional non-confidential context" value={values.additional_context} error={errors.additional_context} helper="Add only information needed to understand the evaluation." onChange={update}/>
        </fieldset>
        <p className={styles.privacy}>{page.form.privacyNotice.replace('Privacy Policy.','')}<a href={page.form.privacyHref}>Privacy Policy</a>.</p><div className={styles.submitRow}><button type="submit" disabled={state==='submitting'}>{state==='submitting'?page.form.submittingLabel:page.form.submitLabel}</button><p>{page.form.submitHelper}</p></div>
        {state==='submitting'&&<p role="status" className={styles.srStatus}>{page.form.submittingLabel}</p>}
        {state==='failure'&&(
          <StatePanel refValue={stateRef} kind="failure" heading={page.form.failure.heading} body={page.form.failure.body} action={<button type="button" onClick={()=>void performSubmission()}>{page.form.failure.action}</button>}/>
        )}
        </>}
      </form>
    </section>
  </>
}

function Context({label,value,onRemove,removeOnly=false,targetId}:{label:string;value:string;onRemove:()=>void;removeOnly?:boolean;targetId?:string}){return <div className={styles.contextCard}><small>{label}</small><strong>{value}</strong><span>{!removeOnly&&targetId&&<button type="button" onClick={()=>document.getElementById(targetId)?.focus()}>Change</button>}<button type="button" aria-label={`Remove ${label}`} onClick={onRemove}>Remove</button></span></div>}
function SelectField({id,label,value,error,describedBy,onChange,children}:{id:'grade_id'|'application_id';label:string;value:string;error?:string;describedBy?:string;onChange:(value:string)=>void;children:React.ReactNode}){return <div className={styles.field} data-sample-field={id}><label htmlFor={`sample-${id}`}>{label} <small>Required</small></label><select id={`sample-${id}`} required aria-required="true" aria-invalid={Boolean(error)} aria-describedby={describedBy} value={value} onChange={(event)=>onChange(event.target.value)}>{children}</select>{error&&<p id={`sample-${id}-error`} className={styles.fieldError}>{error}</p>}</div>}
type TextFieldName=Exclude<Field,'grade_id'|'application_id'|'documents_needed'>
function TextField({field,label,value,error,onChange,required=false,type='text',autoComplete,placeholder,helper}:{field:TextFieldName;label:string;value:string;error?:string;onChange:(field:TextFieldName,value:string)=>void;required?:boolean;type?:'text'|'email';autoComplete?:string;placeholder?:string;helper?:string}){const ids=[helper?`sample-${field}-helper`:null,error?`sample-${field}-error`:null].filter(Boolean).join(' ')||undefined;return <div className={styles.field} data-sample-field={field}><label htmlFor={`sample-${field}`}>{label} <small>{required?'Required':'Optional'}</small></label><input id={`sample-${field}`} type={type} required={required} aria-required={required||undefined} aria-invalid={Boolean(error)} aria-describedby={ids} autoComplete={autoComplete} placeholder={placeholder} value={value} onChange={(event)=>onChange(field,event.target.value)}/>{helper&&<p id={`sample-${field}-helper`} className={styles.helper}>{helper}</p>}{error&&<p id={`sample-${field}-error`} className={styles.fieldError}>{error}</p>}</div>}
function TextArea({field,label,value,error,onChange,required=false,placeholder,helper}:{field:TextFieldName;label:string;value:string;error?:string;onChange:(field:TextFieldName,value:string)=>void;required?:boolean;placeholder?:string;helper?:string}){const ids=[helper?`sample-${field}-helper`:null,error?`sample-${field}-error`:null].filter(Boolean).join(' ')||undefined;return <div className={`${styles.field} ${styles.wide}`} data-sample-field={field}><label htmlFor={`sample-${field}`}>{label} <small>{required?'Required':'Optional'}</small></label><textarea id={`sample-${field}`} rows={field==='test_objective'?5:4} required={required} aria-required={required||undefined} aria-invalid={Boolean(error)} aria-describedby={ids} placeholder={placeholder} value={value} onChange={(event)=>onChange(field,event.target.value)}/>{helper&&<p id={`sample-${field}-helper`} className={styles.helper}>{helper}</p>}<span className={styles.counter}>{Array.from(value).length} / {field==='application_other'?500:2000}</span>{error&&<p id={`sample-${field}-error`} className={styles.fieldError}>{error}</p>}</div>}
function StatePanel({refValue,kind,heading,body,action}:{refValue:React.RefObject<HTMLDivElement|null>;kind:'failure'|'success'|'unavailable';heading:string;body:string;action?:React.ReactNode}){return <div ref={refValue} tabIndex={-1} role={kind==='success'?'status':'alert'} className={`${styles.statePanel} ${styles[kind]}`}><h3>{heading}</h3><p>{body}</p>{action}</div>}
