export const products = [
  ['TP-C050', 'Coatings', 'Electrophoretic and general interior coatings'],
  ['TP-C100', 'Coatings', 'Architectural, industrial and decorative coatings'],
  ['TP-C110', 'Coatings', 'Architectural, industrial and decorative coatings'],
  ['TP-C120', 'Coatings', 'Water-based interior and exterior wall emulsion paint'],
  ['TP-C200', 'Coatings', 'High-PVC matte and flat architectural coatings'],
  ['TP-C300', 'Coatings', 'Durable automotive, marine and exterior coatings'],
  ['TP-C310', 'Coatings', 'Durable waterborne automotive and industrial coatings'],
  ['TP-C400', 'Coatings', 'Durable automotive, marine and exterior coatings'],
  ['TP-C410', 'Coatings', 'Durable exterior and protective coatings'],
  ['TP-P100', 'Plastics', 'Polyolefin color masterbatch'],
  ['TP-P110', 'Plastics', 'PET and polyolefin film masterbatch'],
  ['TP-P120', 'Plastics', 'Soft PVC and solar backsheet film'],
  ['TP-P200', 'Plastics', 'Exterior plastics and weather-resistant masterbatch'],
  ['TP-P300', 'Engineering plastics', 'Polycarbonate and engineering plastics'],
  ['TP-P310', 'Engineering plastics', 'Type I LCP and high-temperature plastics'],
  ['TP-P320', 'Engineering plastics', 'High-reflectance polycarbonate'],
  ['TP-P330', 'Engineering plastics', 'UV-resistant engineering plastics'],
  ['TP-I100', 'Printing inks', 'Solvent-based and water-based printing inks'],
  ['TP-I200', 'Printing inks', 'Weather-resistant water-based printing inks'],
  ['TP-PA100', 'Decorative paper', 'Decorating paper and paperboard'],
  ['TP-PA110', 'Decorative paper', 'High-whiteness decorative paper'],
  ['TP-PA120', 'Decorative paper', 'High-whiteness laminated decorative paper'],
  ['TP-S100', 'Solar film', 'EVA and POE photovoltaic white film'],
  ['TP-H100', 'Functional materials', 'Electronic ceramics and selected functional materials'],
  ['TP-U100', 'Multi-application', 'Application-dependent coatings, inks and plastics evaluation'],
] as const;

export const applicationFamilies = [
  ['Coatings', 'Architectural, industrial, automotive and protective coating systems', '09 products'],
  ['Plastics', 'Masterbatch, film, PVC and engineering-resin evaluation', '08 products'],
  ['Printing inks', 'Water-based and solvent-based ink formulation paths', '02 products'],
  ['Decorative paper', 'Paper furnish, whiteness, retention and laminate evaluation', '03 products'],
  ['Solar film', 'Photovoltaic white-film and solar-backsheet systems', '02 products'],
  ['Functional materials', 'Electronic ceramics and selected high-purity applications', '01 product'],
  ['Multi-application', 'Separate qualification paths across coatings, inks and plastics', '01 product'],
] as const;

export const resources = [
  ['01', 'TiO₂ Fundamentals', 'Rutile vs Anatase Titanium Dioxide: How to Choose'],
  ['02', 'TiO₂ Fundamentals', 'Chloride vs Sulfate Process Titanium Dioxide'],
  ['03', 'TiO₂ Fundamentals', 'Why TiO₂ Content Alone Does Not Determine Performance'],
  ['04', 'Performance', 'What Does Oil Absorption Mean in Titanium Dioxide?'],
  ['05', 'Performance', 'What Is CBU in Titanium Dioxide?'],
  ['06', 'Performance', 'How Surface Treatment Changes Titanium Dioxide Performance'],
  ['07', 'Grade Replacement', 'How to Evaluate a Titanium Dioxide Alternative Grade'],
  ['08', 'Application Testing', 'How to Reduce TiO₂ Cost in High-PVC Flat Paint'],
  ['09', 'Application Testing', 'Why Titanium Dioxide Can Cause Yellowing in Polycarbonate'],
  ['10', 'Application Testing', 'How to Choose Titanium Dioxide for Outdoor Durability'],
] as const;
