<?php

declare(strict_types=1);

if (! defined('ABSPATH')) {
    exit;
}

/**
 * @return list<array<string, mixed>>
 */
function tio2_application_field_definitions(): array
{
    return [
        [
            'key' => 'field_tio2_application_id',
            'label' => 'Application ID',
            'name' => 'application_id',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 80,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_level',
            'label' => 'Application Level',
            'name' => 'application_level',
            'type' => 'select',
            'required' => 1,
            'choices' => [
                'hub' => 'Hub',
                'category' => 'Category',
                'detail' => 'Detail',
            ],
            'return_format' => 'value',
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_family',
            'label' => 'Family',
            'name' => 'family',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 120,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_parent_application',
            'label' => 'Parent Application',
            'name' => 'parent_application',
            'type' => 'relationship',
            'required' => 1,
            'conditional_logic' => [
                [[
                    'field' => 'field_tio2_application_level',
                    'operator' => '==',
                    'value' => 'category',
                ]],
                [[
                    'field' => 'field_tio2_application_level',
                    'operator' => '==',
                    'value' => 'detail',
                ]],
            ],
            'post_type' => ['tio2_application'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 1,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_meta_title',
            'label' => 'Meta Title',
            'name' => 'meta_title',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 100,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_meta_description',
            'label' => 'Meta Description',
            'name' => 'meta_description',
            'type' => 'textarea',
            'required' => 1,
            'maxlength' => 220,
            'rows' => 3,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_eyebrow',
            'label' => 'Eyebrow',
            'name' => 'eyebrow',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 80,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_headline',
            'label' => 'Headline',
            'name' => 'headline',
            'type' => 'textarea',
            'required' => 1,
            'maxlength' => 180,
            'rows' => 2,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_direct_answer',
            'label' => 'Direct Answer',
            'name' => 'direct_answer',
            'type' => 'wysiwyg',
            'required' => 1,
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_context',
            'label' => 'Application Context',
            'name' => 'application_context',
            'type' => 'textarea',
            'required' => 1,
            'rows' => 4,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_buyer_problem',
            'label' => 'Buyer Problem',
            'name' => 'buyer_problem',
            'type' => 'textarea',
            'required' => 1,
            'rows' => 4,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_selection_factors',
            'label' => 'Selection Factors',
            'name' => 'selection_factors',
            'type' => 'repeater',
            'required' => 1,
            'min' => 3,
            'max' => 6,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [[
                'key' => 'field_tio2_application_selection_factors_item',
                'label' => 'Item',
                'name' => 'item',
                'type' => 'textarea',
                'required' => 1,
                'rows' => 2,
                'show_in_graphql' => 1,
            ]],
        ],
        [
            'key' => 'field_tio2_application_powder_data_limits',
            'label' => 'Powder Data Limits',
            'name' => 'powder_data_limits',
            'type' => 'textarea',
            'required' => 1,
            'rows' => 4,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_validation_plan',
            'label' => 'Validation Plan',
            'name' => 'validation_plan',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 6,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [[
                'key' => 'field_tio2_application_validation_plan_item',
                'label' => 'Item',
                'name' => 'item',
                'type' => 'textarea',
                'required' => 1,
                'rows' => 2,
                'show_in_graphql' => 1,
            ]],
        ],
        [
            'key' => 'field_tio2_application_customer_inputs',
            'label' => 'Customer Inputs',
            'name' => 'customer_inputs',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 10,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [[
                'key' => 'field_tio2_application_customer_inputs_item',
                'label' => 'Item',
                'name' => 'item',
                'type' => 'textarea',
                'required' => 1,
                'rows' => 2,
                'show_in_graphql' => 1,
            ]],
        ],
        [
            'key' => 'field_tio2_application_body_sections',
            'label' => 'Body Sections',
            'name' => 'body_sections',
            'type' => 'repeater',
            'required' => 1,
            'min' => 2,
            'max' => 12,
            'layout' => 'block',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_application_body_sections_section_id',
                    'label' => 'Section ID',
                    'name' => 'section_id',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_body_sections_heading',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_body_sections_html',
                    'label' => 'HTML',
                    'name' => 'html',
                    'type' => 'wysiwyg',
                    'required' => 1,
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'show_in_graphql' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_tio2_application_starting_products',
            'label' => 'Product Starting Points',
            'name' => 'starting_products',
            'type' => 'repeater',
            'required' => 0,
            'min' => 0,
            'max' => 24,
            'layout' => 'block',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_application_starting_product_id',
                    'label' => 'Product ID',
                    'name' => 'product_id',
                    'type' => 'text',
                    'required' => 1,
                    'maxlength' => 80,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_starting_product_role',
                    'label' => 'Role',
                    'name' => 'role',
                    'type' => 'select',
                    'required' => 1,
                    'choices' => [
                        'primary' => 'Primary',
                        'alternative' => 'Alternative',
                        'candidate' => 'Candidate',
                    ],
                    'return_format' => 'value',
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_starting_product_label',
                    'label' => 'Label',
                    'name' => 'label',
                    'type' => 'text',
                    'required' => 1,
                    'maxlength' => 120,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_starting_product_summary',
                    'label' => 'Summary',
                    'name' => 'summary_html',
                    'type' => 'wysiwyg',
                    'required' => 1,
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'show_in_graphql' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_tio2_application_faq_items',
            'label' => 'FAQ Items',
            'name' => 'faq_items',
            'type' => 'repeater',
            'required' => 1,
            'min' => 4,
            'max' => 6,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_application_faq_items_question',
                    'label' => 'Question',
                    'name' => 'question',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_faq_items_answer',
                    'label' => 'Answer',
                    'name' => 'answer',
                    'type' => 'wysiwyg',
                    'required' => 1,
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'show_in_graphql' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_tio2_application_child_applications',
            'label' => 'Child Applications',
            'name' => 'child_applications',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_application'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_related_applications',
            'label' => 'Related Applications',
            'name' => 'related_applications',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_application'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_related_resources',
            'label' => 'Related Resources',
            'name' => 'related_resources',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_document'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_related_products',
            'label' => 'Related Products',
            'name' => 'related_products',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_product'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_application_ctas',
            'label' => 'Calls to Action',
            'name' => 'ctas',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 3,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_application_ctas_kind',
                    'label' => 'Kind',
                    'name' => 'kind',
                    'type' => 'select',
                    'required' => 1,
                    'choices' => [
                        'request-tds' => 'Request TDS',
                        'discuss-application' => 'Discuss Application',
                        'request-sample' => 'Request Sample',
                    ],
                    'return_format' => 'value',
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_ctas_label',
                    'label' => 'Label',
                    'name' => 'label',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_application_ctas_href',
                    'label' => 'Href',
                    'name' => 'href',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_tio2_application_technical_disclaimer',
            'label' => 'Technical Disclaimer',
            'name' => 'technical_disclaimer',
            'type' => 'wysiwyg',
            'required' => 1,
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'show_in_graphql' => 1,
        ],
    ];
}

/**
 * @return list<array<string, mixed>>
 */
function tio2_resource_field_definitions(): array
{
    return [
        [
            'key' => 'field_tio2_resource_id',
            'label' => 'Resource ID',
            'name' => 'resource_id',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 80,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_kind',
            'label' => 'Resource Kind',
            'name' => 'resource_kind',
            'type' => 'select',
            'required' => 1,
            'choices' => [
                'hub' => 'Hub',
                'article' => 'Article',
                'guide' => 'Guide',
                'comparison' => 'Comparison',
                'testing-method' => 'Testing Method',
                'case-study' => 'Case Study',
            ],
            'return_format' => 'value',
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_cluster',
            'label' => 'Cluster',
            'name' => 'cluster',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 120,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_meta_title',
            'label' => 'Meta Title',
            'name' => 'meta_title',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 60,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_meta_description',
            'label' => 'Meta Description',
            'name' => 'meta_description',
            'type' => 'textarea',
            'required' => 1,
            'maxlength' => 160,
            'rows' => 3,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_eyebrow',
            'label' => 'Eyebrow',
            'name' => 'eyebrow',
            'type' => 'text',
            'required' => 1,
            'maxlength' => 80,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_headline',
            'label' => 'Headline',
            'name' => 'headline',
            'type' => 'textarea',
            'required' => 1,
            'maxlength' => 180,
            'rows' => 2,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_direct_answer',
            'label' => 'Direct Answer',
            'name' => 'direct_answer',
            'type' => 'wysiwyg',
            'required' => 1,
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_key_takeaways',
            'label' => 'Key Takeaways',
            'name' => 'key_takeaways',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 8,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [[
                'key' => 'field_tio2_resource_key_takeaways_item',
                'label' => 'Item',
                'name' => 'item',
                'type' => 'textarea',
                'required' => 1,
                'rows' => 2,
                'show_in_graphql' => 1,
            ]],
        ],
        [
            'key' => 'field_tio2_resource_sections',
            'label' => 'Sections',
            'name' => 'sections',
            'type' => 'repeater',
            'required' => 1,
            'min' => 2,
            'max' => 20,
            'layout' => 'block',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_resource_sections_section_id',
                    'label' => 'Section ID',
                    'name' => 'section_id',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_resource_sections_heading',
                    'label' => 'Heading',
                    'name' => 'heading',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_resource_sections_html',
                    'label' => 'HTML',
                    'name' => 'html',
                    'type' => 'wysiwyg',
                    'required' => 1,
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'show_in_graphql' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_tio2_resource_comparison_table',
            'label' => 'Comparison Table',
            'name' => 'comparison_table',
            'type' => 'group',
            'required' => 0,
            'layout' => 'block',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_resource_comparison_table_columns',
                    'label' => 'Columns',
                    'name' => 'columns',
                    'type' => 'repeater',
                    'required' => 0,
                    'layout' => 'table',
                    'show_in_graphql' => 1,
                    'sub_fields' => [[
                        'key' => 'field_tio2_resource_comparison_table_columns_label',
                        'label' => 'Label',
                        'name' => 'label',
                        'type' => 'text',
                        'required' => 1,
                        'show_in_graphql' => 1,
                    ]],
                ],
                [
                    'key' => 'field_tio2_resource_comparison_table_rows',
                    'label' => 'Rows',
                    'name' => 'rows',
                    'type' => 'repeater',
                    'required' => 0,
                    'layout' => 'row',
                    'show_in_graphql' => 1,
                    'sub_fields' => [[
                        'key' => 'field_tio2_resource_comparison_table_rows_cells',
                        'label' => 'Cells',
                        'name' => 'cells',
                        'type' => 'repeater',
                        'required' => 0,
                        'layout' => 'table',
                        'show_in_graphql' => 1,
                        'sub_fields' => [[
                            'key' => 'field_tio2_resource_comparison_table_rows_cells_value',
                            'label' => 'Value',
                            'name' => 'value',
                            'type' => 'text',
                            'required' => 1,
                            'show_in_graphql' => 1,
                        ]],
                    ]],
                ],
            ],
        ],
        [
            'key' => 'field_tio2_resource_practical_implications',
            'label' => 'Practical Implications',
            'name' => 'practical_implications',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 12,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [[
                'key' => 'field_tio2_resource_practical_implications_item',
                'label' => 'Item',
                'name' => 'item',
                'type' => 'textarea',
                'required' => 1,
                'rows' => 2,
                'show_in_graphql' => 1,
            ]],
        ],
        [
            'key' => 'field_tio2_resource_common_mistakes',
            'label' => 'Common Mistakes',
            'name' => 'common_mistakes',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 12,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [[
                'key' => 'field_tio2_resource_common_mistakes_item',
                'label' => 'Item',
                'name' => 'item',
                'type' => 'textarea',
                'required' => 1,
                'rows' => 2,
                'show_in_graphql' => 1,
            ]],
        ],
        [
            'key' => 'field_tio2_resource_evaluation_method',
            'label' => 'Evaluation Method',
            'name' => 'evaluation_method',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 12,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [[
                'key' => 'field_tio2_resource_evaluation_method_item',
                'label' => 'Item',
                'name' => 'item',
                'type' => 'textarea',
                'required' => 1,
                'rows' => 2,
                'show_in_graphql' => 1,
            ]],
        ],
        [
            'key' => 'field_tio2_resource_faq_items',
            'label' => 'FAQ Items',
            'name' => 'faq_items',
            'type' => 'repeater',
            'required' => 1,
            'min' => 4,
            'max' => 6,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_resource_faq_items_question',
                    'label' => 'Question',
                    'name' => 'question',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_resource_faq_items_answer',
                    'label' => 'Answer',
                    'name' => 'answer',
                    'type' => 'wysiwyg',
                    'required' => 1,
                    'tabs' => 'visual',
                    'toolbar' => 'basic',
                    'media_upload' => 0,
                    'show_in_graphql' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_tio2_resource_child_resources',
            'label' => 'Child Resources',
            'name' => 'child_resources',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_document'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_related_applications',
            'label' => 'Related Applications',
            'name' => 'related_applications',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_application'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_related_resources',
            'label' => 'Related Resources',
            'name' => 'related_resources',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_document'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_related_products',
            'label' => 'Related Products',
            'name' => 'related_products',
            'type' => 'relationship',
            'required' => 0,
            'post_type' => ['tio2_product'],
            'filters' => ['search'],
            'return_format' => 'id',
            'max' => 24,
            'show_in_graphql' => 1,
        ],
        [
            'key' => 'field_tio2_resource_ctas',
            'label' => 'Calls to Action',
            'name' => 'ctas',
            'type' => 'repeater',
            'required' => 1,
            'min' => 1,
            'max' => 2,
            'layout' => 'row',
            'show_in_graphql' => 1,
            'sub_fields' => [
                [
                    'key' => 'field_tio2_resource_ctas_kind',
                    'label' => 'Kind',
                    'name' => 'kind',
                    'type' => 'select',
                    'required' => 1,
                    'choices' => [
                        'request-tds' => 'Request TDS',
                        'discuss-application' => 'Discuss Application',
                    ],
                    'return_format' => 'value',
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_resource_ctas_label',
                    'label' => 'Label',
                    'name' => 'label',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
                [
                    'key' => 'field_tio2_resource_ctas_href',
                    'label' => 'Href',
                    'name' => 'href',
                    'type' => 'text',
                    'required' => 1,
                    'show_in_graphql' => 1,
                ],
            ],
        ],
        [
            'key' => 'field_tio2_resource_technical_disclaimer',
            'label' => 'Technical Disclaimer',
            'name' => 'technical_disclaimer',
            'type' => 'wysiwyg',
            'required' => 1,
            'tabs' => 'visual',
            'toolbar' => 'basic',
            'media_upload' => 0,
            'show_in_graphql' => 1,
        ],
    ];
}

function tio2_register_application_resource_acf_fields(): void
{
    if (! function_exists('acf_add_local_field_group')) {
        return;
    }

    acf_add_local_field_group([
        'key' => 'group_tio2_application_fields',
        'title' => 'Application',
        'fields' => tio2_application_field_definitions(),
        'location' => [[
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'tio2_application',
            ],
            [
                'param' => 'post_taxonomy',
                'operator' => '==',
                'value' => 'site_scope:tio2-a',
            ],
        ]],
        'show_in_graphql' => 0,
    ]);

    acf_add_local_field_group([
        'key' => 'group_tio2_resource_fields',
        'title' => 'Technical Resource',
        'fields' => tio2_resource_field_definitions(),
        'location' => [[
            [
                'param' => 'post_type',
                'operator' => '==',
                'value' => 'tio2_document',
            ],
            [
                'param' => 'post_taxonomy',
                'operator' => '==',
                'value' => 'site_scope:tio2-a',
            ],
        ]],
        'show_in_graphql' => 0,
    ]);
}
